name: CustomBlocks
main: de.d151l.custom.block.CustomBlocks
version: 1.0-SNAPSHOT
author: D151l

api-version: 1.20

description: The plugin adds the plugins sids base for custom blocks.

libraries:
  - commons-io:commons-io:2.6

commands:
  cgive:
    description: Gives a custom block to the player.
    usage: /cgive <block> [amount]
    permission: customblocks.give
    aliases:
        - customgive
        - givecustom
        - givecustomblock
        - givecustomblocks
        - givecb
        - gcb